import { minsFromNow } from "../utils/dateUtils";
import { aiClassifyFood, aiUrgency } from "../utils/aiServices";

export const DEMO_ACCOUNTS = [
  {
    email: "user@foodbridge.org",
    role: "USER", // Access to both Donor & Receiver hubs
    userType: "USER",
    name: "Ramesh Rao",
    cellNo: "+91 98480 12345",
    houseName: "Flat 402, Sri Sai Nilayam",
    street: "Road No 10, Banjara Hills",
    pincode: "500034",
    city: "Hyderabad, Telangana",
    org: "Green Leaf Kitchens Hyderabad",
  },
  {
    email: "receiver@foodbridge.org",
    role: "USER",
    userType: "USER",
    name: "Anitha Reddy",
    cellNo: "+91 94401 56789",
    houseName: "Plot 45, Sneha Seva Nilayam",
    dropPoint: "Sneha Home Main Gate, Pillar 104",
    street: "Hitec City Main Road, Madhapur",
    pincode: "500081",
    city: "Hyderabad, Telangana",
    org: "Sneha Orphanage & Community Care",
  },
  {
    email: "delivery@foodbridge.org",
    role: "DELIVERY_PARTNER",
    userType: "DELIVERY_PARTNER",
    name: "Kiran Kumar",
    cellNo: "+91 99887 65432",
    vehicle: "Hero Electric Scooty (TS 09 AB 1234)",
    org: "FoodBridge Express Couriers Hyderabad",
  },
];

export const DEMO_PASSWORD = "FoodBridge#2026";

// Hyderabad, Telangana Receivers / Shelters Pool
export const RECEIVERS_POOL = [
  {
    id: "r1",
    name: "Sneha Orphanage & Care Home",
    contactPerson: "Anitha Reddy",
    contact: "+91 94401 56789",
    houseName: "Plot 45, Sneha Nilayam",
    dropPoint: "Main Gate, Near Pillar 104",
    street: "Hitec City Main Road, Madhapur",
    pincode: "500081",
    city: "Hyderabad, Telangana",
    address: "Plot 45, Hitec City Main Road, Madhapur, Hyderabad - 500081",
    lat: 17.4483,
    lng: 78.3808,
    distanceKm: 3.2,
    capacity: 70,
    verified: true,
  },
  {
    id: "r2",
    name: "Aasra Community Food Kitchen",
    contactPerson: "Dr. Venkat Rao",
    contact: "+91 98490 22334",
    houseName: "D.No 8-2-293, Aasra Bhavan",
    dropPoint: "Kitchen Receiving Counter",
    street: "Road No 14, Banjara Hills",
    pincode: "500034",
    city: "Hyderabad, Telangana",
    address: "Road No 14, Banjara Hills, Hyderabad - 500034",
    lat: 17.4156,
    lng: 78.4357,
    distanceKm: 2.1,
    capacity: 90,
    verified: true,
  },
  {
    id: "r3",
    name: "Grace Children Home & Shelter",
    contactPerson: "Sister Mary",
    contact: "+91 97000 88991",
    houseName: "Bldg 12, St. Jude Compound",
    dropPoint: "Dining Hall Rear Gate",
    street: "Clock Tower Area, Secunderabad",
    pincode: "500003",
    city: "Hyderabad, Telangana",
    address: "Clock Tower Road, Secunderabad, Hyderabad - 500003",
    lat: 17.4399,
    lng: 78.4983,
    distanceKm: 6.4,
    capacity: 55,
    verified: true,
  },
  {
    id: "r4",
    name: "Navajeevan Old Age & Night Shelter",
    contactPerson: "K. Satyanarayana",
    contact: "+91 98661 44556",
    houseName: "House 3-4-102, Navajeevan Trust",
    dropPoint: "Front Reception Desk",
    street: "Near Bus Station, Dilsukhnagar",
    pincode: "500060",
    city: "Hyderabad, Telangana",
    address: "Near Dilsukhnagar Metro, Hyderabad - 500060",
    lat: 17.3688,
    lng: 78.5247,
    distanceKm: 7.8,
    capacity: 45,
    verified: false,
  },
];

export const MONTHLY_DATA = [
  { month: "Apr", donations: 68, meals: 1850 },
  { month: "May", donations: 92, meals: 2600 },
  { month: "Jun", donations: 118, meals: 3450 },
  { month: "Jul", donations: 145, meals: 4200 },
  { month: "Aug", donations: 180, meals: 5380 },
  { month: "Sep", donations: 215, meals: 6490 },
];

export const CATEGORY_SPLIT = [
  { name: "Cooked Meals (Biryani/Curries)", value: 45 },
  { name: "Bakery & Breads", value: 18 },
  { name: "Fresh Fruits & Veg", value: 16 },
  { name: "Packaged Food", value: 11 },
  { name: "Dairy & Beverages", value: 10 },
];

export function seedDonations() {
  const base = [
    {
      foodName: "Hyderabadi Dum Veg Biryani & Mirchi Ka Salan",
      qty: 65,
      unit: "meals",
      veg: true,
      donorName: "Ramesh Rao — Royal Caterers",
      donorPhone: "+91 98480 12345",
      donorHouse: "Bldg 4A, Royal Towers",
      donorStreet: "Road No 36, Jubilee Hills",
      donorPincode: "500033",
      pickupAddress: "Bldg 4A, Road No 36, Jubilee Hills, Hyderabad - 500033",
      pickupLat: 17.4319,
      pickupLng: 78.4073,
      deliveryName: "Sneha Orphanage & Care Home",
      receiverPhone: "+91 94401 56789",
      receiverDropPoint: "Main Gate, Near Pillar 104",
      receiverHouse: "Plot 45, Sneha Nilayam",
      receiverStreet: "Hitec City Main Road, Madhapur",
      receiverPincode: "500081",
      deliveryAddress: "Plot 45, Hitec City Main Road, Madhapur, Hyderabad - 500081",
      deliveryLat: 17.4483,
      deliveryLng: 78.3808,
      mins: 45,
      status: "IN_TRANSIT",
      volunteerName: "Kiran Kumar",
      volunteerPhone: "+91 99887 65432",
      courierProgress: 0.65,
    },
    {
      foodName: "Fresh Whole Wheat Breads & Multigrain Buns",
      qty: 40,
      unit: "portions",
      veg: true,
      donorName: "Karachi Bakery Surplus Center",
      donorPhone: "+91 98491 55667",
      donorHouse: "Shop 12-14, Prem Chambers",
      donorStreet: "Banjara Hills Road No 1",
      donorPincode: "500034",
      pickupAddress: "Shop 12-14, Banjara Hills Road No 1, Hyderabad - 500034",
      pickupLat: 17.4156,
      pickupLng: 78.4357,
      deliveryName: null,
      deliveryAddress: null,
      deliveryLat: null,
      deliveryLng: null,
      mins: 180,
      status: "AVAILABLE",
      volunteerName: null,
      courierProgress: 0,
    },
    {
      foodName: "Organic Fresh Seasonal Fruits (Apples & Bananas)",
      qty: 35,
      unit: "kg",
      veg: true,
      donorName: "Ratnadeep Supermarket Surplus",
      donorPhone: "+91 98485 33441",
      donorHouse: "Commercial Complex 5",
      donorStreet: "Gachibowli Outer Ring Road",
      donorPincode: "500032",
      pickupAddress: "Commercial Complex 5, Gachibowli, Hyderabad - 500032",
      pickupLat: 17.4401,
      pickupLng: 78.3489,
      deliveryName: "Aasra Community Food Kitchen",
      receiverPhone: "+91 98490 22334",
      receiverDropPoint: "Kitchen Receiving Counter",
      receiverHouse: "D.No 8-2-293, Aasra Bhavan",
      receiverStreet: "Road No 14, Banjara Hills",
      receiverPincode: "500034",
      deliveryAddress: "Road No 14, Banjara Hills, Hyderabad - 500034",
      deliveryLat: 17.4156,
      deliveryLng: 78.4357,
      mins: 360,
      status: "CLAIMED",
      volunteerName: null,
      courierProgress: 0,
    },
    {
      foodName: "Paneer Butter Masala, Dal Tadka & 80 Rotis",
      qty: 55,
      unit: "meals",
      veg: true,
      donorName: "Paradise Grand Banquets",
      donorPhone: "+91 98499 11223",
      donorHouse: "Plot 22, Banquet Enclave",
      donorStreet: "Begumpet Main Road",
      donorPincode: "500016",
      pickupAddress: "Plot 22, Begumpet Main Road, Hyderabad - 500016",
      pickupLat: 17.4435,
      pickupLng: 78.4682,
      deliveryName: "Grace Children Home & Shelter",
      receiverPhone: "+91 97000 88991",
      receiverDropPoint: "Dining Hall Rear Gate",
      receiverHouse: "Bldg 12, St. Jude Compound",
      receiverStreet: "Clock Tower Area, Secunderabad",
      receiverPincode: "500003",
      deliveryAddress: "Clock Tower Road, Secunderabad, Hyderabad - 500003",
      deliveryLat: 17.4399,
      deliveryLng: 78.4983,
      mins: 90,
      status: "PICKED_UP",
      volunteerName: "Kiran Kumar",
      volunteerPhone: "+91 99887 65432",
      courierProgress: 0.25,
    },
    {
      foodName: "Surplus Corporate Lunch (Rice, Sambar & Poriyal)",
      qty: 80,
      unit: "meals",
      veg: true,
      donorName: "Tech Mahindra Cyber Cafeteria",
      donorPhone: "+91 98480 88776",
      donorHouse: "Tower 2, Cafeteria 3rd Floor",
      donorStreet: "Hitec City Phase 2, Madhapur",
      donorPincode: "500081",
      pickupAddress: "Tower 2, Hitec City Phase 2, Madhapur, Hyderabad - 500081",
      pickupLat: 17.4475,
      pickupLng: 78.3750,
      deliveryName: "Navajeevan Old Age & Night Shelter",
      receiverPhone: "+91 98661 44556",
      receiverDropPoint: "Front Reception Desk",
      receiverHouse: "House 3-4-102, Navajeevan Trust",
      receiverStreet: "Near Bus Station, Dilsukhnagar",
      receiverPincode: "500060",
      deliveryAddress: "Near Dilsukhnagar Metro, Hyderabad - 500060",
      deliveryLat: 17.3688,
      deliveryLng: 78.5247,
      mins: 25,
      status: "DELIVERED",
      volunteerName: "Kiran Kumar",
      volunteerPhone: "+91 99887 65432",
      courierProgress: 1.0,
    },
    {
      foodName: "Assorted Packaged Sandwiches, Rolls & Juices",
      qty: 45,
      unit: "portions",
      veg: true,
      donorName: "Ameerpet Cafe & Bakers",
      donorPhone: "+91 99490 77665",
      donorHouse: "Shop 8, Metro Station Pillar 1022",
      donorStreet: "Ameerpet Crossroads",
      donorPincode: "500038",
      pickupAddress: "Shop 8, Ameerpet Crossroads, Hyderabad - 500038",
      pickupLat: 17.4375,
      pickupLng: 78.4482,
      deliveryName: null,
      deliveryAddress: null,
      deliveryLat: null,
      deliveryLng: null,
      mins: 140,
      status: "AVAILABLE",
      volunteerName: null,
      courierProgress: 0,
    },
  ];

  return base.map((b, i) => {
    const ai = aiClassifyFood(b.foodName);
    const consumeBefore = minsFromNow(b.mins);
    const urg = aiUrgency(b.mins);
    const createdAt = minsFromNow(-Math.floor(Math.random() * 100 + 20));

    const timeline = [{ stage: "Donation Created", at: createdAt }];
    if (["CLAIMED", "PICKED_UP", "IN_TRANSIT", "DELIVERED", "COMPLETED"].includes(b.status)) {
      timeline.push({ stage: "Claimed & Pinned by Receiver", at: minsFromNow(-80) });
    }
    if (["PICKED_UP", "IN_TRANSIT", "DELIVERED", "COMPLETED"].includes(b.status)) {
      timeline.push({ stage: "Delivery Partner Dispatched", at: minsFromNow(-55) });
      timeline.push({ stage: "Food Picked Up from Donor", at: minsFromNow(-35) });
    }
    if (["IN_TRANSIT", "DELIVERED", "COMPLETED"].includes(b.status)) {
      timeline.push({ stage: "In Live GPS Transit", at: minsFromNow(-15) });
    }
    if (["DELIVERED", "COMPLETED"].includes(b.status)) {
      timeline.push({ stage: "Safely Handed Over at Drop Point", at: minsFromNow(-5) });
    }
    if (b.status === "COMPLETED") {
      timeline.push({ stage: "Meal Receipt Confirmed", at: minsFromNow(-1) });
    }

    return {
      id: `fb-hyd-${i + 101}`,
      donorId: b.donorPhone ? `donor_${i + 101}@foodbridge.org` : "user@foodbridge.org",
      donorName: b.donorName,
      donorPhone: b.donorPhone,
      donorHouse: b.donorHouse,
      donorStreet: b.donorStreet,
      donorPincode: b.donorPincode,
      foodName: b.foodName,
      category: ai.category,
      quantity: b.qty,
      unit: b.unit,
      vegetarian: b.veg,
      estimatedPortions: b.qty,
      prepTime: minsFromNow(-45),
      consumeBefore,
      pickupStart: minsFromNow(0),
      pickupEnd: minsFromNow(b.mins),
      pickupAddress: b.pickupAddress,
      pickupLat: b.pickupLat,
      pickupLng: b.pickupLng,
      deliveryName: b.deliveryName,
      receiverPhone: b.receiverPhone || null,
      receiverDropPoint: b.receiverDropPoint || null,
      receiverHouse: b.receiverHouse || null,
      receiverStreet: b.receiverStreet || null,
      receiverPincode: b.receiverPincode || null,
      deliveryAddress: b.deliveryAddress,
      deliveryLat: b.deliveryLat,
      deliveryLng: b.deliveryLng,
      distanceKm: b.deliveryLat ? ((Math.abs(b.pickupLat - b.deliveryLat) + Math.abs(b.pickupLng - b.deliveryLng)) * 75).toFixed(1) : "3.4",
      notes: "Freshly prepared under safe temperature control. Insulated containers provided.",
      status: b.status,
      urgencyLevel: urg.level,
      receiverId: b.status !== "AVAILABLE" ? "receiver@foodbridge.org" : null,
      volunteerId: b.volunteerName ? "delivery@foodbridge.org" : null,
      volunteerName: b.volunteerName,
      volunteerPhone: b.volunteerPhone,
      courierProgress: b.courierProgress || 0,
      createdAt,
      timeline,
    };
  });
}
